import type { MetadataRoute } from "next";

const BASE_URL =
  process.env.NEXT_PUBLIC_SITE_URL ?? process.env.SITE_URL ?? "https://validatehome.com";

const LOCAL_PAGES = [
  { country: "us", geo: "ca" },
  { country: "us", geo: "ny" },
  { country: "us", geo: "ma" },
  { country: "us", geo: "tx" },
  { country: "us", geo: "fl" },
  { country: "us", geo: "il" },
  { country: "us", geo: "pa" },
  { country: "us", geo: "oh" },
  { country: "us", geo: "ga" },
  { country: "us", geo: "nc" },
  { country: "us", geo: "mi" },
  { country: "us", geo: "wa" },
  { country: "us", geo: "co" },
  { country: "us", geo: "az" },
  { country: "us", geo: "or" },
  { country: "us", geo: "nv" },
  { country: "us", geo: "va" },
  { country: "us", geo: "in" },
  { country: "us", geo: "tn" },
  { country: "us", geo: "md" },
  { country: "us", geo: "mo" },
  { country: "us", geo: "wi" },
  { country: "us", geo: "mn" },
  { country: "us", geo: "sc" },
  { country: "us", geo: "al" },
  { country: "us", geo: "la" },
  { country: "us", geo: "ky" },
  { country: "us", geo: "ok" },
  { country: "us", geo: "ct" },
  { country: "us", geo: "ut" },
  { country: "us", geo: "ia" },
  { country: "us", geo: "ar" },
  { country: "us", geo: "ms" },
  { country: "us", geo: "ks" },
  { country: "us", geo: "nm" },
  { country: "us", geo: "ne" },
  { country: "us", geo: "wv" },
  { country: "us", geo: "id" },
  { country: "us", geo: "hi" },
  { country: "us", geo: "nh" },
  { country: "us", geo: "me" },
  { country: "us", geo: "mt" },
  { country: "us", geo: "ri" },
  { country: "us", geo: "de" },
  { country: "us", geo: "sd" },
  { country: "us", geo: "nd" },
  { country: "us", geo: "vt" },
  { country: "us", geo: "wy" },
  { country: "us", geo: "ak" },
  { country: "uk", geo: "london" },
  { country: "uk", geo: "manchester" },
  { country: "uk", geo: "birmingham" },
  { country: "uk", geo: "scotland" },
  { country: "uk", geo: "wales" },
  { country: "uk", geo: "edinburgh" },
  { country: "uk", geo: "cardiff" },
  { country: "uk", geo: "leeds" },
  { country: "uk", geo: "sheffield" },
  { country: "uk", geo: "liverpool" },
  { country: "uk", geo: "newcastle" },
  { country: "uk", geo: "cambridge" },
  { country: "uk", geo: "oxford" },
  { country: "uk", geo: "bristol" },
  { country: "uk", geo: "coventry" },
  { country: "uk", geo: "nottingham" },
  { country: "uk", geo: "leicester" },
  { country: "uk", geo: "southampton" },
  { country: "uk", geo: "portsmouth" },
  { country: "uk", geo: "brighton" },
  { country: "uk", geo: "canterbury" },
  { country: "uk", geo: "norwich" },
  { country: "uk", geo: "peterborough" },
  { country: "uk", geo: "stoke-on-trent" },
  { country: "uk", geo: "derby" },
  { country: "uk", geo: "middlesbrough" },
  { country: "uk", geo: "hull" },
  { country: "uk", geo: "aberdeen" },
  { country: "uk", geo: "dundee" },
  { country: "uk", geo: "glasgow" },
  { country: "uk", geo: "swansea" },
  { country: "uk", geo: "newport" },
  { country: "uk", geo: "belfast" },
  { country: "uk", geo: "exeter" },
  { country: "uk", geo: "plymouth" },
  { country: "uk", geo: "bournemouth" },
  { country: "uk", geo: "york" },
  { country: "uk", geo: "bath" },
  { country: "uk", geo: "reading" },
  { country: "uk", geo: "slough" },
  { country: "uk", geo: "milton-keynes" },
  { country: "uk", geo: "st-albans" },
  { country: "uk", geo: "chelmsford" },
  { country: "uk", geo: "guildford" },
  { country: "uk", geo: "wakefield" },
  { country: "uk", geo: "oldham" },
  { country: "uk", geo: "bolton" },
  { country: "uk", geo: "wigan" },
  { country: "uk", geo: "sunderland" },
  { country: "uk", geo: "durham" },
  { country: "uk", geo: "carlisle" },
  { country: "uk", geo: "taunton" },
  { country: "uk", geo: "gloucester" },
  { country: "au", geo: "nsw" },
  { country: "au", geo: "vic" },
  { country: "au", geo: "qld" },
  { country: "au", geo: "wa" },
  { country: "au", geo: "sa" },
  { country: "au", geo: "tas" },
  { country: "au", geo: "nt" },
  { country: "au", geo: "act" },
  { country: "au", geo: "sydney" },
  { country: "au", geo: "melbourne" },
  { country: "au", geo: "brisbane" },
  { country: "au", geo: "perth" },
  { country: "au", geo: "adelaide" },
  { country: "au", geo: "hobart" },
  { country: "au", geo: "darwin" },
  { country: "au", geo: "canberra" },
  { country: "au", geo: "newcastle-au" },
  { country: "au", geo: "wollongong" },
  { country: "au", geo: "geelong" },
  { country: "au", geo: "ballarat" },
  { country: "au", geo: "bendigo" },
  { country: "au", geo: "gold-coast" },
  { country: "au", geo: "toowoomba" },
  { country: "au", geo: "rockhampton" },
  { country: "au", geo: "cairns" },
  { country: "au", geo: "townsville" },
  { country: "au", geo: "freemantle" },
  { country: "au", geo: "launceston" },
  { country: "au", geo: "alice-springs" },
  { country: "au", geo: "cairns" },
  { country: "au", geo: "sunshine-coast" },
  { country: "au", geo: "central-coast" },
  { country: "au", geo: "ipswich" },
  { country: "au", geo: "mackay" },
  { country: "au", geo: "bunbury" },
  { country: "au", geo: "geraldton" },
  { country: "au", geo: "albury" },
  { country: "au", geo: "wagga-wagga" },
  { country: "au", geo: "cairns" },
  { country: "au", geo: "toowoomba" },
  { country: "au", geo: "hobart" },
  { country: "au", geo: "launceston" },
  { country: "au", geo: "devonport" },
  { country: "au", geo: "palmerston" },
  { country: "au", geo: "belconnen" },
  { country: "au", geo: "tuggeranong" },
  { country: "ca", geo: "on" },
  { country: "ca", geo: "bc" },
  { country: "ca", geo: "qc" },
  { country: "ca", geo: "ab" },
  { country: "ca", geo: "ns" },
  { country: "ca", geo: "mb" },
  { country: "ca", geo: "sk" },
  { country: "ca", geo: "nb" },
  { country: "ca", geo: "nl" },
  { country: "ca", geo: "pe" },
  { country: "ca", geo: "toronto" },
  { country: "ca", geo: "montreal" },
  { country: "ca", geo: "vancouver" },
  { country: "ca", geo: "ottawa" },
  { country: "ca", geo: "calgary" },
  { country: "ca", geo: "edmonton" },
  { country: "ca", geo: "halifax" },
  { country: "ca", geo: "winnipeg" },
  { country: "ca", geo: "saskatoon" },
  { country: "ca", geo: "regina" },
  { country: "ca", geo: "moncton" },
  { country: "ca", geo: "st-johns" },
  { country: "ca", geo: "charlottetown" },
  { country: "ca", geo: "st-catharines" },
  { country: "ca", geo: "kitchener" },
  { country: "ca", geo: "london-on" },
  { country: "ca", geo: "hamilton" },
  { country: "ca", geo: "north-bay" },
  { country: "ca", geo: "barrie" },
  { country: "ca", geo: "kingston" },
  { country: "ca", geo: "mississauga" },
  { country: "ca", geo: "markham" },
  { country: "ca", geo: "kelowna" },
  { country: "ca", geo: "abbotsford" },
  { country: "ca", geo: "victoria" },
  { country: "ca", geo: "surrey" },
  { country: "ca", geo: "burnaby" },
  { country: "ca", geo: "quebec-city" },
  { country: "ca", geo: "longueuil" },
  { country: "ca", geo: "laval" },
  { country: "ca", geo: "gatineau" },
  { country: "ca", geo: "brossard" },
  { country: "ca", geo: "airdrie" },
  { country: "ca", geo: "lloydminster" },
  { country: "ca", geo: "truro" },
  { country: "ca", geo: "kentville" },
  { country: "ca", geo: "bathurst" },
  { country: "ca", geo: "fredericton" },
  { country: "ca", geo: "dieppe" },
  { country: "ca", geo: "swift-current" },
  { country: "ca", geo: "moose-jaw" },
  { country: "ca", geo: "prince-george" },
  { country: "ca", geo: "nanaimo" },
  { country: "ca", geo: "maple-ridge" },
  { country: "ca", geo: "guelph" },
  { country: "ca", geo: "oakville" },
];

export default function sitemap(): MetadataRoute.Sitemap {
  const now = new Date();

  const staticUrls = [
    { url: BASE_URL, priority: 1, changeFrequency: "daily" as const },
    { url: `${BASE_URL}/programs`, priority: 0.9, changeFrequency: "daily" as const },
    { url: `${BASE_URL}/programs/us`, priority: 0.9, changeFrequency: "daily" as const },
    { url: `${BASE_URL}/programs/uk`, priority: 0.9, changeFrequency: "daily" as const },
    { url: `${BASE_URL}/programs/au`, priority: 0.9, changeFrequency: "daily" as const },
    { url: `${BASE_URL}/programs/ca`, priority: 0.9, changeFrequency: "daily" as const },
    { url: `${BASE_URL}/search`, priority: 0.8, changeFrequency: "daily" as const },
    { url: `${BASE_URL}/calculator/heat_pump`, priority: 0.8, changeFrequency: "weekly" as const },
    { url: `${BASE_URL}/calculator/solar`, priority: 0.8, changeFrequency: "weekly" as const },
  ];

  const uniqueLocalPages = Array.from(
    new Map(LOCAL_PAGES.map((page) => [`${page.country}/${page.geo}`, page])).values(),
  );

  const localUrls = uniqueLocalPages.map((page) => ({
    url: `${BASE_URL}/local/${page.country}/${page.geo}`,
    lastModified: now,
    changeFrequency: "weekly" as const,
    priority: 0.7,
  }));

  return [
    ...staticUrls.map((page) => ({
      url: page.url,
      lastModified: now,
      changeFrequency: page.changeFrequency,
      priority: page.priority,
    })),
    ...localUrls,
  ];
}
