/**
 * Seed script for ValidateHome database.
 * Run with: pnpm db:seed
 */
import { sql } from "drizzle-orm";
import { createDb } from "./index.js";
import { benefits } from "./schema/benefit.js";
import { productCategories, programCategories } from "./schema/category.js";
import { geoMappings } from "./schema/geo.js";
import { jurisdictions } from "./schema/jurisdiction.js";
import { programs } from "./schema/program.js";
import { loadDotEnvIfPresent } from "./utils/load-env.js";

const logInfo = (message: string): void => {
  process.stdout.write(`${message}\n`);
};

const logError = (message: string): void => {
  process.stderr.write(`${message}\n`);
};

function must<T>(value: T | undefined, label: string): T {
  if (value === undefined) {
    throw new Error(`Missing required seed value: ${label}`);
  }
  return value;
}

async function seed() {
  loadDotEnvIfPresent();
  const connectionString = process.env.DATABASE_URL;
  if (!connectionString) {
    logError("DATABASE_URL environment variable is required");
    process.exitCode = 1;
    return;
  }

  const db = createDb(connectionString);
  try {
    logInfo("Seeding database...");

    const existingPrograms = await db.select({ count: sql<number>`count(*)::int` }).from(programs);
    if ((existingPrograms[0]?.count ?? 0) > 0) {
      logInfo("Seed data already present; skipping.");
      return;
    }

    await db.transaction(async (tx) => {
      // --- Jurisdictions ---
      const federalRows = await tx
        .insert(jurisdictions)
        .values([
          { name: "United States (Federal)", isoCode: "US", country: "US", level: "federal" },
          { name: "United Kingdom (Federal)", isoCode: "UK", country: "UK", level: "federal" },
          { name: "Australia (Federal)", isoCode: "AU", country: "AU", level: "federal" },
          { name: "Canada (Federal)", isoCode: "CA", country: "CA", level: "federal" },
        ])
        .returning();
      const usFederal = must(federalRows[0], "usFederal");
      const ukFederal = must(federalRows[1], "ukFederal");
      const auFederal = must(federalRows[2], "auFederal");
      const caFederal = must(federalRows[3], "caFederal");
      const usFederalId = usFederal.id;
      const ukFederalId = ukFederal.id;
      const auFederalId = auFederal.id;
      const caFederalId = caFederal.id;
      logInfo("  Created 4 federal jurisdictions");

      const stateRows = await tx
        .insert(jurisdictions)
        .values([
          {
            name: "California",
            isoCode: "US-CA",
            country: "US" as const,
            level: "state" as const,
            parentId: usFederalId,
          },
          {
            name: "New York",
            isoCode: "US-NY",
            country: "US" as const,
            level: "state" as const,
            parentId: usFederalId,
          },
          {
            name: "Massachusetts",
            isoCode: "US-MA",
            country: "US" as const,
            level: "state" as const,
            parentId: usFederalId,
          },
          {
            name: "England",
            isoCode: "UK-ENG",
            country: "UK" as const,
            level: "state" as const,
            parentId: ukFederalId,
          },
          {
            name: "New South Wales",
            isoCode: "AU-NSW",
            country: "AU" as const,
            level: "state" as const,
            parentId: auFederalId,
          },
          {
            name: "British Columbia",
            isoCode: "CA-BC",
            country: "CA" as const,
            level: "state" as const,
            parentId: caFederalId,
          },
        ])
        .returning();
      const usCa = must(stateRows[0], "usCa");
      const usNy = must(stateRows[1], "usNy");
      const usMa = must(stateRows[2], "usMa");
      const ukEng = must(stateRows[3], "ukEng");
      const auNsw = must(stateRows[4], "auNsw");
      const caBc = must(stateRows[5], "caBc");
      const usCaId = usCa.id;
      const usNyId = usNy.id;
      const usMaId = usMa.id;
      const ukEngId = ukEng.id;
      const auNswId = auNsw.id;
      const caBcId = caBc.id;
      logInfo("  Created 6 state/province jurisdictions");

      // Additional jurisdictions for Phase 1 (30+ programs target)
      const additionalStateRows = await tx
        .insert(jurisdictions)
        .values([
          // US States
          {
            name: "Texas",
            isoCode: "US-TX",
            country: "US" as const,
            level: "state" as const,
            parentId: usFederalId,
          },
          {
            name: "Florida",
            isoCode: "US-FL",
            country: "US" as const,
            level: "state" as const,
            parentId: usFederalId,
          },
          {
            name: "Illinois",
            isoCode: "US-IL",
            country: "US" as const,
            level: "state" as const,
            parentId: usFederalId,
          },
          {
            name: "Pennsylvania",
            isoCode: "US-PA",
            country: "US" as const,
            level: "state" as const,
            parentId: usFederalId,
          },
          {
            name: "Ohio",
            isoCode: "US-OH",
            country: "US" as const,
            level: "state" as const,
            parentId: usFederalId,
          },
          {
            name: "Georgia",
            isoCode: "US-GA",
            country: "US" as const,
            level: "state" as const,
            parentId: usFederalId,
          },
          {
            name: "North Carolina",
            isoCode: "US-NC",
            country: "US" as const,
            level: "state" as const,
            parentId: usFederalId,
          },
          {
            name: "Michigan",
            isoCode: "US-MI",
            country: "US" as const,
            level: "state" as const,
            parentId: usFederalId,
          },
          {
            name: "Washington",
            isoCode: "US-WA",
            country: "US" as const,
            level: "state" as const,
            parentId: usFederalId,
          },
          {
            name: "Colorado",
            isoCode: "US-CO",
            country: "US" as const,
            level: "state" as const,
            parentId: usFederalId,
          },
          // UK Countries
          {
            name: "Scotland",
            isoCode: "UK-SCT",
            country: "UK" as const,
            level: "state" as const,
            parentId: ukFederalId,
          },
          {
            name: "Wales",
            isoCode: "UK-WLS",
            country: "UK" as const,
            level: "state" as const,
            parentId: ukFederalId,
          },
          // AU States
          {
            name: "Victoria",
            isoCode: "AU-VIC",
            country: "AU" as const,
            level: "state" as const,
            parentId: auFederalId,
          },
          {
            name: "Queensland",
            isoCode: "AU-QLD",
            country: "AU" as const,
            level: "state" as const,
            parentId: auFederalId,
          },
          {
            name: "Western Australia",
            isoCode: "AU-WA",
            country: "AU" as const,
            level: "state" as const,
            parentId: auFederalId,
          },
          {
            name: "South Australia",
            isoCode: "AU-SA",
            country: "AU" as const,
            level: "state" as const,
            parentId: auFederalId,
          },
          // CA Provinces
          {
            name: "Ontario",
            isoCode: "CA-ON",
            country: "CA" as const,
            level: "state" as const,
            parentId: caFederalId,
          },
          {
            name: "Quebec",
            isoCode: "CA-QC",
            country: "CA" as const,
            level: "state" as const,
            parentId: caFederalId,
          },
          {
            name: "Alberta",
            isoCode: "CA-AB",
            country: "CA" as const,
            level: "state" as const,
            parentId: caFederalId,
          },
          {
            name: "Nova Scotia",
            isoCode: "CA-NS",
            country: "CA" as const,
            level: "state" as const,
            parentId: caFederalId,
          },
        ])
        .returning();

      const usTxId = must(additionalStateRows[0]?.id, "usTx");
      const usFlId = must(additionalStateRows[1]?.id, "usFl");
      const usIlId = must(additionalStateRows[2]?.id, "usIl");
      const usPaId = must(additionalStateRows[3]?.id, "usPa");
      const usOhId = must(additionalStateRows[4]?.id, "usOh");
      const usGaId = must(additionalStateRows[5]?.id, "usGa");
      const usNcId = must(additionalStateRows[6]?.id, "usNc");
      const usMiId = must(additionalStateRows[7]?.id, "usMi");
      const usWaId = must(additionalStateRows[8]?.id, "usWa");
      const usCoId = must(additionalStateRows[9]?.id, "usCo");
      const ukSctId = must(additionalStateRows[10]?.id, "ukSct");
      const ukWlsId = must(additionalStateRows[11]?.id, "ukWls");
      const auVicId = must(additionalStateRows[12]?.id, "auVic");
      const auQldId = must(additionalStateRows[13]?.id, "auQld");
      const auWaId = must(additionalStateRows[14]?.id, "auWa");
      const auSaId = must(additionalStateRows[15]?.id, "auSa");
      const caOnId = must(additionalStateRows[16]?.id, "caOn");
      const caQcId = must(additionalStateRows[17]?.id, "caQc");
      const caAbId = must(additionalStateRows[18]?.id, "caAb");
      const caNsId = must(additionalStateRows[19]?.id, "caNs");
      logInfo("  Created 20 additional state/province jurisdictions");

      // --- Product Categories ---
      const categoryData = [
        {
          name: "Heat Pumps",
          slug: "heat-pumps",
          description: "Air source and ground source heat pumps",
          iconName: "thermometer",
        },
        {
          name: "Solar Panels",
          slug: "solar-panels",
          description: "Residential solar PV systems",
          iconName: "sun",
        },
        {
          name: "Insulation",
          slug: "insulation",
          description: "Wall, roof, and floor insulation",
          iconName: "home",
        },
        {
          name: "EV Chargers",
          slug: "ev-chargers",
          description: "Electric vehicle charging stations",
          iconName: "zap",
        },
        {
          name: "Windows & Doors",
          slug: "windows-doors",
          description: "Energy-efficient windows and doors",
          iconName: "layout",
        },
        {
          name: "Water Heaters",
          slug: "water-heaters",
          description: "Heat pump and solar water heaters",
          iconName: "droplet",
        },
        {
          name: "Smart Thermostats",
          slug: "smart-thermostats",
          description: "Connected heating controls",
          iconName: "settings",
        },
        {
          name: "Battery Storage",
          slug: "battery-storage",
          description: "Home battery storage systems",
          iconName: "battery",
        },
      ];
      const categories = await tx.insert(productCategories).values(categoryData).returning();
      logInfo("  Created 8 product categories");

      const categoryIdBySlug = (slug: string): string =>
        must(
          categories.find((c) => c.slug === slug),
          `${slug} category`,
        ).id;

      const heatPumpCatId = categoryIdBySlug("heat-pumps");
      const solarCatId = categoryIdBySlug("solar-panels");
      const insulationCatId = categoryIdBySlug("insulation");
      const evChargerCatId = categoryIdBySlug("ev-chargers");
      const waterHeaterCatId = categoryIdBySlug("water-heaters");
      const batteryStorageCatId = categoryIdBySlug("battery-storage");

      // --- Programs ---
      const programData = [
        // US Federal
        {
          jurisdictionId: usFederalId,
          name: "IRS 25C Tax Credit",
          slug: "irs-25c-tax-credit",
          description:
            "Federal tax credit for energy-efficient home improvements including heat pumps, insulation, and windows.",
          status: "open" as const,
          budgetTotal: "999999999.00",
          programUrl:
            "https://www.irs.gov/credits-deductions/energy-efficient-home-improvement-credit",
          categoryIds: [heatPumpCatId, insulationCatId],
          benefitData: [
            {
              type: "tax_credit" as const,
              maxAmount: "2000.00",
              percentage: 30,
              currency: "USD" as const,
              description: "30% of cost, up to $2,000 for heat pumps",
            },
          ],
        },
        {
          jurisdictionId: usFederalId,
          name: "IRS 25D Residential Clean Energy Credit",
          slug: "irs-25d-residential-clean-energy",
          description:
            "Federal tax credit for solar panels, battery storage, and geothermal heat pumps.",
          status: "open" as const,
          programUrl: "https://www.irs.gov/credits-deductions/residential-clean-energy-credit",
          categoryIds: [solarCatId],
          benefitData: [
            {
              type: "tax_credit" as const,
              percentage: 30,
              currency: "USD" as const,
              description: "30% of cost with no cap",
            },
          ],
        },
        // US California
        {
          jurisdictionId: usCaId,
          name: "TECH Clean California",
          slug: "tech-clean-california",
          description: "California incentive program for heat pump HVAC and water heaters.",
          status: "open" as const,
          budgetTotal: "120000000.00",
          budgetRemaining: "45000000.00",
          budgetPctUsed: 62,
          programUrl: "https://www.techcleanca.com",
          categoryIds: [heatPumpCatId, waterHeaterCatId],
          benefitData: [
            {
              type: "rebate" as const,
              maxAmount: "3000.00",
              currency: "USD" as const,
              description: "Up to $3,000 for qualifying heat pump systems",
            },
          ],
        },
        // US New York
        {
          jurisdictionId: usNyId,
          name: "NY Clean Heat",
          slug: "ny-clean-heat",
          description: "New York State incentive for heat pump installations.",
          status: "open" as const,
          programUrl: "https://cleanheat.ny.gov",
          categoryIds: [heatPumpCatId],
          benefitData: [
            {
              type: "rebate" as const,
              maxAmount: "4000.00",
              currency: "USD" as const,
              description: "Up to $4,000 per ton for air-source heat pumps",
            },
          ],
        },
        // US Massachusetts
        {
          jurisdictionId: usMaId,
          name: "Mass Save Heat Pump Program",
          slug: "mass-save-heat-pump",
          description: "Massachusetts utility-sponsored rebates for heat pump installations.",
          status: "open" as const,
          programUrl: "https://www.masssave.com/residential/rebates-and-incentives/heat-pumps",
          categoryIds: [heatPumpCatId],
          benefitData: [
            {
              type: "rebate" as const,
              maxAmount: "10000.00",
              currency: "USD" as const,
              description: "Up to $10,000 for whole-home heat pump systems",
            },
          ],
        },
        // UK
        {
          jurisdictionId: ukFederalId,
          name: "Boiler Upgrade Scheme",
          slug: "boiler-upgrade-scheme",
          description: "UK government grant for replacing fossil fuel heating with heat pumps.",
          status: "open" as const,
          budgetTotal: "450000000.00",
          budgetRemaining: "180000000.00",
          budgetPctUsed: 60,
          programUrl: "https://www.gov.uk/apply-boiler-upgrade-scheme",
          categoryIds: [heatPumpCatId],
          benefitData: [
            {
              type: "grant" as const,
              maxAmount: "7500.00",
              currency: "GBP" as const,
              description: "£7,500 grant for air source heat pumps",
            },
          ],
        },
        {
          jurisdictionId: ukFederalId,
          name: "ECO4",
          slug: "eco4-scheme",
          description:
            "Energy Company Obligation scheme providing insulation and heating upgrades for low-income households.",
          status: "open" as const,
          programUrl:
            "https://www.ofgem.gov.uk/environmental-and-social-schemes/energy-company-obligation-eco",
          categoryIds: [insulationCatId, heatPumpCatId],
          benefitData: [
            {
              type: "grant" as const,
              maxAmount: "10000.00",
              currency: "GBP" as const,
              description: "Fully funded measures for eligible households",
            },
          ],
        },
        // Australia
        {
          jurisdictionId: auFederalId,
          name: "Small-scale Renewable Energy Scheme",
          slug: "small-scale-renewable-energy-scheme",
          description:
            "Federal scheme providing Small-scale Technology Certificates (STCs) for solar and heat pumps.",
          status: "open" as const,
          programUrl:
            "https://www.cleanenergyregulator.gov.au/RET/About-the-Renewable-Energy-Target/The-small-scale-renewable-energy-scheme",
          categoryIds: [solarCatId, heatPumpCatId],
          benefitData: [
            {
              type: "rebate" as const,
              maxAmount: "3000.00",
              currency: "AUD" as const,
              description: "Value varies by location and system size via STCs",
            },
          ],
        },
        {
          jurisdictionId: auNswId,
          name: "NSW Energy Savings Scheme",
          slug: "nsw-energy-savings-scheme",
          description: "NSW scheme providing certificates for energy-efficient upgrades.",
          status: "open" as const,
          programUrl:
            "https://www.energy.nsw.gov.au/nsw-plans-and-progress/regulation-and-policy/energy-security-safeguard/energy-savings-scheme",
          categoryIds: [heatPumpCatId, insulationCatId],
          benefitData: [
            {
              type: "rebate" as const,
              maxAmount: "4000.00",
              currency: "AUD" as const,
              description: "Discounts via Energy Savings Certificates",
            },
          ],
        },
        // Canada
        {
          jurisdictionId: caFederalId,
          name: "Canada Greener Homes Grant",
          slug: "canada-greener-homes-grant",
          description:
            "Federal grant for home energy retrofits including heat pumps, insulation, and solar.",
          status: "waitlist" as const,
          budgetTotal: "2600000000.00",
          budgetRemaining: "400000000.00",
          budgetPctUsed: 85,
          programUrl:
            "https://natural-resources.canada.ca/energy-efficiency/homes/canada-greener-homes-initiative/canada-greener-homes-grant/23441",
          categoryIds: [heatPumpCatId, insulationCatId, solarCatId],
          benefitData: [
            {
              type: "grant" as const,
              maxAmount: "5000.00",
              currency: "CAD" as const,
              description: "Up to $5,000 for eligible retrofits",
            },
          ],
        },
        {
          jurisdictionId: caBcId,
          name: "CleanBC Better Homes",
          slug: "cleanbc-better-homes",
          description: "BC provincial rebates for heat pumps, insulation, and EV chargers.",
          status: "open" as const,
          programUrl: "https://betterhomesbc.ca",
          categoryIds: [heatPumpCatId, insulationCatId, evChargerCatId],
          benefitData: [
            {
              type: "rebate" as const,
              maxAmount: "6000.00",
              currency: "CAD" as const,
              description: "Up to $6,000 for heat pump installations",
            },
          ],
        },
        // US Texas
        {
          jurisdictionId: usTxId,
          name: "Texas Energy Efficiency Program",
          slug: "texas-energy-efficiency",
          description: "Texas utility rebates for energy-efficient home upgrades.",
          status: "open" as const,
          programUrl: "https://www.texasefficiency.com",
          categoryIds: [heatPumpCatId, insulationCatId],
          benefitData: [
            {
              type: "rebate" as const,
              maxAmount: "1500.00",
              currency: "USD" as const,
              description: "Up to $1,500 for heat pumps",
            },
          ],
        },
        // US Florida
        {
          jurisdictionId: usFlId,
          name: "Florida Clean Energy Rebates",
          slug: "florida-clean-energy",
          description: "Florida state rebates for solar and energy-efficient upgrades.",
          status: "open" as const,
          programUrl: "https://www.floridapsi.com",
          categoryIds: [solarCatId, heatPumpCatId],
          benefitData: [
            {
              type: "rebate" as const,
              maxAmount: "2000.00",
              currency: "USD" as const,
              description: "Up to $2,000 for solar",
            },
          ],
        },
        // US Illinois
        {
          jurisdictionId: usIlId,
          name: "Illinois Energy Transition",
          slug: "illinois-energy-transition",
          description: "Illinois program for clean energy transitions in homes.",
          status: "open" as const,
          programUrl: "https://www.illinoiscleanenergy.com",
          categoryIds: [heatPumpCatId, solarCatId, insulationCatId],
          benefitData: [
            {
              type: "rebate" as const,
              maxAmount: "4000.00",
              currency: "USD" as const,
              description: "Up to $4,000 for heat pumps",
            },
          ],
        },
        // US Pennsylvania
        {
          jurisdictionId: usPaId,
          name: "Pennsylvania Sunshine Program",
          slug: "pennsylvania-sunshine",
          description: "Pennsylvania solar and energy efficiency program.",
          status: "open" as const,
          programUrl: "https://www.papuc.com/solar",
          categoryIds: [solarCatId, heatPumpCatId],
          benefitData: [
            {
              type: "rebate" as const,
              maxAmount: "3000.00",
              currency: "USD" as const,
              description: "Up to $3,000 for solar",
            },
          ],
        },
        // US Ohio
        {
          jurisdictionId: usOhId,
          name: "Ohio Home Energy Assistance",
          slug: "ohio-home-energy",
          description: "Ohio program for low-to-moderate income home energy improvements.",
          status: "open" as const,
          programUrl: "https://www.energyhelp.ohio.gov",
          categoryIds: [heatPumpCatId, insulationCatId],
          benefitData: [
            {
              type: "rebate" as const,
              maxAmount: "2500.00",
              currency: "USD" as const,
              description: "Up to $2,500 for upgrades",
            },
          ],
        },
        // US Georgia
        {
          jurisdictionId: usGaId,
          name: "Georgia Green Initiative",
          slug: "georgia-green-initiative",
          description: "Georgia state incentives for energy-efficient homes.",
          status: "open" as const,
          programUrl: "https://www.georgiagreenenergy.org",
          categoryIds: [solarCatId, heatPumpCatId],
          benefitData: [
            {
              type: "rebate" as const,
              maxAmount: "2500.00",
              currency: "USD" as const,
              description: "Up to $2,500 for solar",
            },
          ],
        },
        // US North Carolina
        {
          jurisdictionId: usNcId,
          name: "North Carolina EnergyWise",
          slug: "north-carolina-energywise",
          description: "North Carolina program for residential energy efficiency.",
          status: "open" as const,
          programUrl: "https://www.energywisenc.com",
          categoryIds: [heatPumpCatId, insulationCatId, solarCatId],
          benefitData: [
            {
              type: "rebate" as const,
              maxAmount: "3500.00",
              currency: "USD" as const,
              description: "Up to $3,500 for heat pumps",
            },
          ],
        },
        // US Michigan
        {
          jurisdictionId: usMiId,
          name: "Michigan Energy Efficiency",
          slug: "michigan-energy-efficiency",
          description: "Michigan utility-sponsored rebates for home efficiency.",
          status: "open" as const,
          programUrl: "https://www.michiganenergy.gov",
          categoryIds: [heatPumpCatId, insulationCatId],
          benefitData: [
            {
              type: "rebate" as const,
              maxAmount: "2000.00",
              currency: "USD" as const,
              description: "Up to $2,000 for insulation",
            },
          ],
        },
        // US Washington
        {
          jurisdictionId: usWaId,
          name: "Washington Clean Energy",
          slug: "washington-clean-energy",
          description: "Washington state incentives for heat pumps and solar.",
          status: "open" as const,
          programUrl: "https://www.energy.washington.gov",
          categoryIds: [heatPumpCatId, solarCatId],
          benefitData: [
            {
              type: "rebate" as const,
              maxAmount: "5000.00",
              currency: "USD" as const,
              description: "Up to $5,000 for heat pumps",
            },
          ],
        },
        // US Colorado
        {
          jurisdictionId: usCoId,
          name: "Colorado Energy Code",
          slug: "colorado-energy-code",
          description: "Colorado residential energy efficiency incentives.",
          status: "open" as const,
          programUrl: "https://www.colorado.gov/energy",
          categoryIds: [solarCatId, heatPumpCatId, insulationCatId],
          benefitData: [
            {
              type: "rebate" as const,
              maxAmount: "3000.00",
              currency: "USD" as const,
              description: "Up to $3,000 for solar",
            },
          ],
        },
        // UK Scotland
        {
          jurisdictionId: ukSctId,
          name: "Home Energy Scotland",
          slug: "home-energy-scotland",
          description: "Scottish government energy efficiency and heating grants.",
          status: "open" as const,
          programUrl: "https://www.homeenergyscotland.org",
          categoryIds: [heatPumpCatId, insulationCatId],
          benefitData: [
            {
              type: "grant" as const,
              maxAmount: "7500.00",
              currency: "GBP" as const,
              description: "Up to £7,500 for heat pumps",
            },
          ],
        },
        // UK Wales
        {
          jurisdictionId: ukWlsId,
          name: "Wales Energy Service",
          slug: "wales-energy-service",
          description: "Welsh government energy efficiency scheme.",
          status: "open" as const,
          programUrl: "https://www.energysavertrust.org.uk",
          categoryIds: [heatPumpCatId, insulationCatId],
          benefitData: [
            {
              type: "grant" as const,
              maxAmount: "6000.00",
              currency: "GBP" as const,
              description: "Up to £6,000 for insulation",
            },
          ],
        },
        // AU Victoria
        {
          jurisdictionId: auVicId,
          name: "Victoria Solar Homes",
          slug: "victoria-solar-homes",
          description: "Victoria state rebates for solar panels and battery storage.",
          status: "open" as const,
          budgetTotal: "190000000.00",
          budgetRemaining: "85000000.00",
          budgetPctUsed: 55,
          programUrl: "https://www.solar.vic.gov.au",
          categoryIds: [solarCatId, batteryStorageCatId],
          benefitData: [
            {
              type: "rebate" as const,
              maxAmount: "1400.00",
              currency: "AUD" as const,
              description: "Up to $1,400 for solar",
            },
          ],
        },
        // AU Queensland
        {
          jurisdictionId: auQldId,
          name: "Queensland Energy Saver",
          slug: "queensland-energy-saver",
          description: "Queensland government rebates for energy-efficient upgrades.",
          status: "open" as const,
          programUrl: "https://www.qld.gov.au/energy",
          categoryIds: [solarCatId, heatPumpCatId],
          benefitData: [
            {
              type: "rebate" as const,
              maxAmount: "3000.00",
              currency: "AUD" as const,
              description: "Up to $3,000 for solar",
            },
          ],
        },
        // AU Western Australia
        {
          jurisdictionId: auWaId,
          name: "WA Energy Upgrade",
          slug: "wa-energy-upgrade",
          description: "Western Australia home energy efficiency program.",
          status: "open" as const,
          programUrl: "https://www.energy.wa.gov.au",
          categoryIds: [heatPumpCatId, insulationCatId],
          benefitData: [
            {
              type: "rebate" as const,
              maxAmount: "2000.00",
              currency: "AUD" as const,
              description: "Up to $2,000 for upgrades",
            },
          ],
        },
        // AU South Australia
        {
          jurisdictionId: auSaId,
          name: "SA Residential Energy Efficiency",
          slug: "sa-residential-energy",
          description: "South Australia home energy efficiency scheme.",
          status: "open" as const,
          programUrl: "https://www.sa.gov.au/energy",
          categoryIds: [solarCatId, heatPumpCatId, insulationCatId],
          benefitData: [
            {
              type: "rebate" as const,
              maxAmount: "3000.00",
              currency: "AUD" as const,
              description: "Up to $3,000 for solar",
            },
          ],
        },
        // CA Ontario
        {
          jurisdictionId: caOnId,
          name: "Ontario Energy Saver",
          slug: "ontario-energy-saver",
          description: "Ontario provincial rebates for home energy retrofits.",
          status: "open" as const,
          programUrl: "https://www.ontarioenergyboard.ca",
          categoryIds: [heatPumpCatId, insulationCatId],
          benefitData: [
            {
              type: "rebate" as const,
              maxAmount: "5000.00",
              currency: "CAD" as const,
              description: "Up to $5,000 for heat pumps",
            },
          ],
        },
        // CA Quebec
        {
          jurisdictionId: caQcId,
          name: "Quebec Rénoclimat",
          slug: "quebec-renoclimat",
          description: "Quebec provincial program for home energy improvements.",
          status: "open" as const,
          programUrl: "https://www.renoclimat.gouv.qc.ca",
          categoryIds: [heatPumpCatId, insulationCatId],
          benefitData: [
            {
              type: "rebate" as const,
              maxAmount: "4000.00",
              currency: "CAD" as const,
              description: "Up to $4,000 for insulation",
            },
          ],
        },
        // CA Alberta
        {
          jurisdictionId: caAbId,
          name: "Alberta Energy Efficiency",
          slug: "alberta-energy-efficiency",
          description: "Alberta residential energy efficiency program.",
          status: "open" as const,
          programUrl: "https://www.alberta.ca/energy-efficiency",
          categoryIds: [solarCatId, heatPumpCatId],
          benefitData: [
            {
              type: "rebate" as const,
              maxAmount: "3000.00",
              currency: "CAD" as const,
              description: "Up to $3,000 for solar",
            },
          ],
        },
        // CA Nova Scotia
        {
          jurisdictionId: caNsId,
          name: "Nova Scotia Efficiency",
          slug: "nova-scotia-efficiency",
          description: "Nova Scotia home energy efficiency program.",
          status: "open" as const,
          programUrl: "https://www.efficiencyns.ca",
          categoryIds: [heatPumpCatId, insulationCatId],
          benefitData: [
            {
              type: "rebate" as const,
              maxAmount: "5000.00",
              currency: "CAD" as const,
              description: "Up to $5,000 for heat pumps",
            },
          ],
        },
      ];

      for (const p of programData) {
        const { categoryIds, benefitData, ...programFields } = p;
        const [insertedProgram] = await tx.insert(programs).values(programFields).returning();
        const program = must(insertedProgram, `program ${programFields.slug}`);

        if (benefitData.length > 0) {
          await tx
            .insert(benefits)
            .values(benefitData.map((b) => ({ ...b, programId: program.id })));
        }

        if (categoryIds.length > 0) {
          await tx
            .insert(programCategories)
            .values(categoryIds.map((catId) => ({ programId: program.id, categoryId: catId })));
        }
      }
      logInfo(`  Created ${programData.length} programs with benefits and categories`);

      // --- Geo Mappings (top ZIP/postcodes) ---
      const geoData = [
        // US
        {
          postalCode: "90210",
          country: "US" as const,
          jurisdictionIds: [usFederalId, usCaId],
          city: "Beverly Hills",
          stateProvince: "CA",
          lat: "34.0901168",
          lng: "-118.4064506",
        },
        {
          postalCode: "10001",
          country: "US" as const,
          jurisdictionIds: [usFederalId, usNyId],
          city: "New York",
          stateProvince: "NY",
          lat: "40.7484284",
          lng: "-73.9967422",
        },
        {
          postalCode: "02101",
          country: "US" as const,
          jurisdictionIds: [usFederalId, usMaId],
          city: "Boston",
          stateProvince: "MA",
          lat: "42.3700998",
          lng: "-71.0588801",
        },
        {
          postalCode: "94102",
          country: "US" as const,
          jurisdictionIds: [usFederalId, usCaId],
          city: "San Francisco",
          stateProvince: "CA",
          lat: "37.7790262",
          lng: "-122.4199061",
        },
        {
          postalCode: "95814",
          country: "US" as const,
          jurisdictionIds: [usFederalId, usCaId],
          city: "Sacramento",
          stateProvince: "CA",
          lat: "38.5815719",
          lng: "-121.4943996",
        },
        // UK
        {
          postalCode: "SW1A 1AA",
          country: "UK" as const,
          jurisdictionIds: [ukFederalId, ukEngId],
          city: "London",
          stateProvince: "England",
          lat: "51.5014",
          lng: "-0.1419",
        },
        {
          postalCode: "M1 1AE",
          country: "UK" as const,
          jurisdictionIds: [ukFederalId, ukEngId],
          city: "Manchester",
          stateProvince: "England",
          lat: "53.4808",
          lng: "-2.2426",
        },
        {
          postalCode: "B1 1BB",
          country: "UK" as const,
          jurisdictionIds: [ukFederalId, ukEngId],
          city: "Birmingham",
          stateProvince: "England",
          lat: "52.4862",
          lng: "-1.8904",
        },
        // AU
        {
          postalCode: "2000",
          country: "AU" as const,
          jurisdictionIds: [auFederalId, auNswId],
          city: "Sydney",
          stateProvince: "NSW",
          lat: "-33.8688",
          lng: "151.2093",
        },
        {
          postalCode: "2600",
          country: "AU" as const,
          jurisdictionIds: [auFederalId],
          city: "Canberra",
          stateProvince: "ACT",
          lat: "-35.2809",
          lng: "149.1300",
        },
        // CA
        {
          postalCode: "V6B 1A1",
          country: "CA" as const,
          jurisdictionIds: [caFederalId, caBcId],
          city: "Vancouver",
          stateProvince: "BC",
          lat: "49.2827",
          lng: "-123.1207",
        },
        {
          postalCode: "K1A 0B1",
          country: "CA" as const,
          jurisdictionIds: [caFederalId],
          city: "Ottawa",
          stateProvince: "ON",
          lat: "45.4215",
          lng: "-75.6972",
        },
        // US Extended (50 total)
        {
          postalCode: "75201",
          country: "US" as const,
          jurisdictionIds: [usFederalId, usTxId],
          city: "Dallas",
          stateProvince: "TX",
          lat: "32.7767",
          lng: "-96.7970",
        },
        {
          postalCode: "77001",
          country: "US" as const,
          jurisdictionIds: [usFederalId, usTxId],
          city: "Houston",
          stateProvince: "TX",
          lat: "29.7604",
          lng: "-95.3698",
        },
        {
          postalCode: "78701",
          country: "US" as const,
          jurisdictionIds: [usFederalId, usTxId],
          city: "Austin",
          stateProvince: "TX",
          lat: "30.2672",
          lng: "-97.7431",
        },
        {
          postalCode: "33101",
          country: "US" as const,
          jurisdictionIds: [usFederalId, usFlId],
          city: "Miami",
          stateProvince: "FL",
          lat: "25.7617",
          lng: "-80.1918",
        },
        {
          postalCode: "32801",
          country: "US" as const,
          jurisdictionIds: [usFederalId, usFlId],
          city: "Orlando",
          stateProvince: "FL",
          lat: "28.5383",
          lng: "-81.3792",
        },
        {
          postalCode: "60601",
          country: "US" as const,
          jurisdictionIds: [usFederalId, usIlId],
          city: "Chicago",
          stateProvince: "IL",
          lat: "41.8781",
          lng: "-87.6298",
        },
        {
          postalCode: "19101",
          country: "US" as const,
          jurisdictionIds: [usFederalId, usPaId],
          city: "Philadelphia",
          stateProvince: "PA",
          lat: "39.9526",
          lng: "-75.1652",
        },
        {
          postalCode: "43201",
          country: "US" as const,
          jurisdictionIds: [usFederalId, usOhId],
          city: "Columbus",
          stateProvince: "OH",
          lat: "39.9612",
          lng: "-82.9988",
        },
        {
          postalCode: "30301",
          country: "US" as const,
          jurisdictionIds: [usFederalId, usGaId],
          city: "Atlanta",
          stateProvince: "GA",
          lat: "33.7490",
          lng: "-84.3880",
        },
        {
          postalCode: "27601",
          country: "US" as const,
          jurisdictionIds: [usFederalId, usNcId],
          city: "Raleigh",
          stateProvince: "NC",
          lat: "35.7796",
          lng: "-78.6382",
        },
        {
          postalCode: "48201",
          country: "US" as const,
          jurisdictionIds: [usFederalId, usMiId],
          city: "Detroit",
          stateProvince: "MI",
          lat: "42.3314",
          lng: "-83.0458",
        },
        {
          postalCode: "98101",
          country: "US" as const,
          jurisdictionIds: [usFederalId, usWaId],
          city: "Seattle",
          stateProvince: "WA",
          lat: "47.6062",
          lng: "-122.3321",
        },
        {
          postalCode: "80201",
          country: "US" as const,
          jurisdictionIds: [usFederalId, usCoId],
          city: "Denver",
          stateProvince: "CO",
          lat: "39.7392",
          lng: "-104.9903",
        },
        {
          postalCode: "85001",
          country: "US" as const,
          jurisdictionIds: [usFederalId],
          city: "Phoenix",
          stateProvince: "AZ",
          lat: "33.4484",
          lng: "-112.0740",
        },
        {
          postalCode: "97201",
          country: "US" as const,
          jurisdictionIds: [usFederalId],
          city: "Portland",
          stateProvince: "OR",
          lat: "45.5152",
          lng: "-122.6784",
        },
        {
          postalCode: "89101",
          country: "US" as const,
          jurisdictionIds: [usFederalId],
          city: "Las Vegas",
          stateProvince: "NV",
          lat: "36.1699",
          lng: "-115.1398",
        },
        {
          postalCode: "22201",
          country: "US" as const,
          jurisdictionIds: [usFederalId],
          city: "Arlington",
          stateProvince: "VA",
          lat: "38.8816",
          lng: "-77.0910",
        },
        {
          postalCode: "46201",
          country: "US" as const,
          jurisdictionIds: [usFederalId],
          city: "Indianapolis",
          stateProvince: "IN",
          lat: "39.7684",
          lng: "-86.1581",
        },
        {
          postalCode: "37201",
          country: "US" as const,
          jurisdictionIds: [usFederalId],
          city: "Nashville",
          stateProvince: "TN",
          lat: "36.1627",
          lng: "-86.7816",
        },
        {
          postalCode: "21201",
          country: "US" as const,
          jurisdictionIds: [usFederalId],
          city: "Baltimore",
          stateProvince: "MD",
          lat: "39.2904",
          lng: "-76.6122",
        },
        {
          postalCode: "63101",
          country: "US" as const,
          jurisdictionIds: [usFederalId],
          city: "St. Louis",
          stateProvince: "MO",
          lat: "38.6270",
          lng: "-90.1994",
        },
        {
          postalCode: "53201",
          country: "US" as const,
          jurisdictionIds: [usFederalId],
          city: "Milwaukee",
          stateProvince: "WI",
          lat: "43.0389",
          lng: "-87.9065",
        },
        {
          postalCode: "55401",
          country: "US" as const,
          jurisdictionIds: [usFederalId],
          city: "Minneapolis",
          stateProvince: "MN",
          lat: "44.9778",
          lng: "-93.2650",
        },
        {
          postalCode: "29201",
          country: "US" as const,
          jurisdictionIds: [usFederalId],
          city: "Columbia",
          stateProvince: "SC",
          lat: "34.0007",
          lng: "-81.0348",
        },
        {
          postalCode: "35201",
          country: "US" as const,
          jurisdictionIds: [usFederalId],
          city: "Birmingham",
          stateProvince: "AL",
          lat: "33.5207",
          lng: "-86.8025",
        },
        {
          postalCode: "70112",
          country: "US" as const,
          jurisdictionIds: [usFederalId],
          city: "New Orleans",
          stateProvince: "LA",
          lat: "29.9511",
          lng: "-90.0715",
        },
        {
          postalCode: "40201",
          country: "US" as const,
          jurisdictionIds: [usFederalId],
          city: "Louisville",
          stateProvince: "KY",
          lat: "38.2527",
          lng: "-85.7585",
        },
        {
          postalCode: "73101",
          country: "US" as const,
          jurisdictionIds: [usFederalId],
          city: "Oklahoma City",
          stateProvince: "OK",
          lat: "35.4676",
          lng: "-97.5164",
        },
        {
          postalCode: "06101",
          country: "US" as const,
          jurisdictionIds: [usFederalId],
          city: "Hartford",
          stateProvince: "CT",
          lat: "41.7658",
          lng: "-72.6734",
        },
        {
          postalCode: "84101",
          country: "US" as const,
          jurisdictionIds: [usFederalId],
          city: "Salt Lake City",
          stateProvince: "UT",
          lat: "40.7608",
          lng: "-111.8910",
        },
        {
          postalCode: "50309",
          country: "US" as const,
          jurisdictionIds: [usFederalId],
          city: "Des Moines",
          stateProvince: "IA",
          lat: "41.5868",
          lng: "-93.6250",
        },
        {
          postalCode: "72201",
          country: "US" as const,
          jurisdictionIds: [usFederalId],
          city: "Little Rock",
          stateProvince: "AR",
          lat: "34.7465",
          lng: "-92.2896",
        },
        {
          postalCode: "39530",
          country: "US" as const,
          jurisdictionIds: [usFederalId],
          city: "Biloxi",
          stateProvince: "MS",
          lat: "30.3960",
          lng: "-88.8853",
        },
        {
          postalCode: "66601",
          country: "US" as const,
          jurisdictionIds: [usFederalId],
          city: "Topeka",
          stateProvince: "KS",
          lat: "39.0473",
          lng: "-95.6752",
        },
        {
          postalCode: "89501",
          country: "US" as const,
          jurisdictionIds: [usFederalId],
          city: "Reno",
          stateProvince: "NV",
          lat: "39.5296",
          lng: "-119.8138",
        },
        {
          postalCode: "87101",
          country: "US" as const,
          jurisdictionIds: [usFederalId],
          city: "Albuquerque",
          stateProvince: "NM",
          lat: "35.0844",
          lng: "-106.6504",
        },
        {
          postalCode: "68501",
          country: "US" as const,
          jurisdictionIds: [usFederalId],
          city: "Lincoln",
          stateProvince: "NE",
          lat: "40.8258",
          lng: "-96.6852",
        },
        {
          postalCode: "25301",
          country: "US" as const,
          jurisdictionIds: [usFederalId],
          city: "Charleston",
          stateProvince: "WV",
          lat: "38.3498",
          lng: "-81.6326",
        },
        {
          postalCode: "83701",
          country: "US" as const,
          jurisdictionIds: [usFederalId],
          city: "Boise",
          stateProvince: "ID",
          lat: "43.6150",
          lng: "-116.2023",
        },
        {
          postalCode: "96813",
          country: "US" as const,
          jurisdictionIds: [usFederalId],
          city: "Honolulu",
          stateProvince: "HI",
          lat: "21.3069",
          lng: "-157.8583",
        },
        {
          postalCode: "03301",
          country: "US" as const,
          jurisdictionIds: [usFederalId],
          city: "Concord",
          stateProvince: "NH",
          lat: "43.2081",
          lng: "-71.5376",
        },
        {
          postalCode: "04101",
          country: "US" as const,
          jurisdictionIds: [usFederalId],
          city: "Portland",
          stateProvince: "ME",
          lat: "43.6591",
          lng: "-70.2568",
        },
        {
          postalCode: "59601",
          country: "US" as const,
          jurisdictionIds: [usFederalId],
          city: "Helena",
          stateProvince: "MT",
          lat: "46.5891",
          lng: "-112.0391",
        },
        {
          postalCode: "02901",
          country: "US" as const,
          jurisdictionIds: [usFederalId],
          city: "Providence",
          stateProvince: "RI",
          lat: "41.8240",
          lng: "-71.4128",
        },
        {
          postalCode: "19901",
          country: "US" as const,
          jurisdictionIds: [usFederalId],
          city: "Dover",
          stateProvince: "DE",
          lat: "39.1582",
          lng: "-75.5244",
        },
        {
          postalCode: "57401",
          country: "US" as const,
          jurisdictionIds: [usFederalId],
          city: "Aberdeen",
          stateProvince: "SD",
          lat: "45.4647",
          lng: "-98.4865",
        },
        {
          postalCode: "58102",
          country: "US" as const,
          jurisdictionIds: [usFederalId],
          city: "Fargo",
          stateProvince: "ND",
          lat: "46.8772",
          lng: "-96.7898",
        },
        {
          postalCode: "05602",
          country: "US" as const,
          jurisdictionIds: [usFederalId],
          city: "Montpelier",
          stateProvince: "VT",
          lat: "44.2601",
          lng: "-72.5754",
        },
        {
          postalCode: "82001",
          country: "US" as const,
          jurisdictionIds: [usFederalId],
          city: "Cheyenne",
          stateProvince: "WY",
          lat: "41.1400",
          lng: "-104.8197",
        },
        {
          postalCode: "99501",
          country: "US" as const,
          jurisdictionIds: [usFederalId],
          city: "Anchorage",
          stateProvince: "AK",
          lat: "61.2181",
          lng: "-149.9003",
        },
        // UK Extended (50 total)
        {
          postalCode: "EH1 1AA",
          country: "UK" as const,
          jurisdictionIds: [ukFederalId, ukSctId],
          city: "Edinburgh",
          stateProvince: "Scotland",
          lat: "55.9533",
          lng: "-3.1883",
        },
        {
          postalCode: "CF10 1AA",
          country: "UK" as const,
          jurisdictionIds: [ukFederalId, ukWlsId],
          city: "Cardiff",
          stateProvince: "Wales",
          lat: "51.4816",
          lng: "-3.1791",
        },
        {
          postalCode: "LS1 1AA",
          country: "UK" as const,
          jurisdictionIds: [ukFederalId, ukEngId],
          city: "Leeds",
          stateProvince: "England",
          lat: "53.8008",
          lng: "-1.5491",
        },
        {
          postalCode: "S1 1AA",
          country: "UK" as const,
          jurisdictionIds: [ukFederalId, ukEngId],
          city: "Sheffield",
          stateProvince: "England",
          lat: "53.3811",
          lng: "-1.4701",
        },
        {
          postalCode: "L1 1AA",
          country: "UK" as const,
          jurisdictionIds: [ukFederalId, ukEngId],
          city: "Liverpool",
          stateProvince: "England",
          lat: "53.4084",
          lng: "-2.9916",
        },
        {
          postalCode: "NE1 1AA",
          country: "UK" as const,
          jurisdictionIds: [ukFederalId, ukEngId],
          city: "Newcastle",
          stateProvince: "England",
          lat: "54.9783",
          lng: "-1.6178",
        },
        {
          postalCode: "CB1 1AA",
          country: "UK" as const,
          jurisdictionIds: [ukFederalId, ukEngId],
          city: "Cambridge",
          stateProvince: "England",
          lat: "52.2053",
          lng: "0.1218",
        },
        {
          postalCode: "OX1 1AA",
          country: "UK" as const,
          jurisdictionIds: [ukFederalId, ukEngId],
          city: "Oxford",
          stateProvince: "England",
          lat: "51.7520",
          lng: "-1.2577",
        },
        {
          postalCode: "BS1 1AA",
          country: "UK" as const,
          jurisdictionIds: [ukFederalId, ukEngId],
          city: "Bristol",
          stateProvince: "England",
          lat: "51.4545",
          lng: "-2.5879",
        },
        {
          postalCode: "CV1 1AA",
          country: "UK" as const,
          jurisdictionIds: [ukFederalId, ukEngId],
          city: "Coventry",
          stateProvince: "England",
          lat: "52.4068",
          lng: "-1.5197",
        },
        {
          postalCode: "NG1 1AA",
          country: "UK" as const,
          jurisdictionIds: [ukFederalId, ukEngId],
          city: "Nottingham",
          stateProvince: "England",
          lat: "52.9548",
          lng: "-1.1581",
        },
        {
          postalCode: "LE1 1AA",
          country: "UK" as const,
          jurisdictionIds: [ukFederalId, ukEngId],
          city: "Leicester",
          stateProvince: "England",
          lat: "52.6369",
          lng: "-1.1398",
        },
        {
          postalCode: "SO14 1AA",
          country: "UK" as const,
          jurisdictionIds: [ukFederalId, ukEngId],
          city: "Southampton",
          stateProvince: "England",
          lat: "50.9097",
          lng: "-1.4044",
        },
        {
          postalCode: "PO1 1AA",
          country: "UK" as const,
          jurisdictionIds: [ukFederalId, ukEngId],
          city: "Portsmouth",
          stateProvince: "England",
          lat: "50.7990",
          lng: "-1.0913",
        },
        {
          postalCode: "BN1 1AA",
          country: "UK" as const,
          jurisdictionIds: [ukFederalId, ukEngId],
          city: "Brighton",
          stateProvince: "England",
          lat: "50.8225",
          lng: "-0.1372",
        },
        {
          postalCode: "CT1 1AA",
          country: "UK" as const,
          jurisdictionIds: [ukFederalId, ukEngId],
          city: "Canterbury",
          stateProvince: "England",
          lat: "51.2790",
          lng: "1.0799",
        },
        {
          postalCode: "NR1 1AA",
          country: "UK" as const,
          jurisdictionIds: [ukFederalId, ukEngId],
          city: "Norwich",
          stateProvince: "England",
          lat: "52.6309",
          lng: "1.2974",
        },
        {
          postalCode: "PE1 1AA",
          country: "UK" as const,
          jurisdictionIds: [ukFederalId, ukEngId],
          city: "Peterborough",
          stateProvince: "England",
          lat: "52.5695",
          lng: "-0.2405",
        },
        {
          postalCode: "ST1 1AA",
          country: "UK" as const,
          jurisdictionIds: [ukFederalId, ukEngId],
          city: "Stoke-on-Trent",
          stateProvince: "England",
          lat: "53.0027",
          lng: "-2.1794",
        },
        {
          postalCode: "DE1 1AA",
          country: "UK" as const,
          jurisdictionIds: [ukFederalId, ukEngId],
          city: "Derby",
          stateProvince: "England",
          lat: "52.9225",
          lng: "-1.4746",
        },
        {
          postalCode: "TS1 1AA",
          country: "UK" as const,
          jurisdictionIds: [ukFederalId, ukEngId],
          city: "Middlesbrough",
          stateProvince: "England",
          lat: "54.5730",
          lng: "-1.2350",
        },
        {
          postalCode: "HU1 1AA",
          country: "UK" as const,
          jurisdictionIds: [ukFederalId, ukEngId],
          city: "Hull",
          stateProvince: "England",
          lat: "53.7446",
          lng: "-0.3350",
        },
        {
          postalCode: "AB1 1AA",
          country: "UK" as const,
          jurisdictionIds: [ukFederalId, ukSctId],
          city: "Aberdeen",
          stateProvince: "Scotland",
          lat: "57.1497",
          lng: "-2.0943",
        },
        {
          postalCode: "DD1 1AA",
          country: "UK" as const,
          jurisdictionIds: [ukFederalId, ukSctId],
          city: "Dundee",
          stateProvince: "Scotland",
          lat: "56.4620",
          lng: "-2.9707",
        },
        {
          postalCode: "G1 1AA",
          country: "UK" as const,
          jurisdictionIds: [ukFederalId, ukSctId],
          city: "Glasgow",
          stateProvince: "Scotland",
          lat: "55.8580",
          lng: "-4.2514",
        },
        {
          postalCode: "SA1 1AA",
          country: "UK" as const,
          jurisdictionIds: [ukFederalId, ukWlsId],
          city: "Swansea",
          stateProvince: "Wales",
          lat: "51.6214",
          lng: "-3.9436",
        },
        {
          postalCode: "NP1 1AA",
          country: "UK" as const,
          jurisdictionIds: [ukFederalId, ukWlsId],
          city: "Newport",
          stateProvince: "Wales",
          lat: "51.5842",
          lng: "-2.9983",
        },
        {
          postalCode: "BT1 1AA",
          country: "UK" as const,
          jurisdictionIds: [ukFederalId],
          city: "Belfast",
          stateProvince: "Northern Ireland",
          lat: "54.5973",
          lng: "-5.9301",
        },
        {
          postalCode: "EX1 1AA",
          country: "UK" as const,
          jurisdictionIds: [ukFederalId, ukEngId],
          city: "Exeter",
          stateProvince: "England",
          lat: "50.7184",
          lng: "-3.5339",
        },
        {
          postalCode: "PL1 1AA",
          country: "UK" as const,
          jurisdictionIds: [ukFederalId, ukEngId],
          city: "Plymouth",
          stateProvince: "England",
          lat: "50.3755",
          lng: "-4.1427",
        },
        {
          postalCode: "BH1 1AA",
          country: "UK" as const,
          jurisdictionIds: [ukFederalId, ukEngId],
          city: "Bournemouth",
          stateProvince: "England",
          lat: "50.7208",
          lng: "-1.9048",
        },
        {
          postalCode: "YO1 1AA",
          country: "UK" as const,
          jurisdictionIds: [ukFederalId, ukEngId],
          city: "York",
          stateProvince: "England",
          lat: "53.9582",
          lng: "-1.0803",
        },
        {
          postalCode: "BA1 1AA",
          country: "UK" as const,
          jurisdictionIds: [ukFederalId, ukEngId],
          city: "Bath",
          stateProvince: "England",
          lat: "51.3758",
          lng: "-2.3599",
        },
        {
          postalCode: "RG1 1AA",
          country: "UK" as const,
          jurisdictionIds: [ukFederalId, ukEngId],
          city: "Reading",
          stateProvince: "England",
          lat: "51.4543",
          lng: "-0.9781",
        },
        {
          postalCode: "SL1 1AA",
          country: "UK" as const,
          jurisdictionIds: [ukFederalId, ukEngId],
          city: "Slough",
          stateProvince: "England",
          lat: "51.5105",
          lng: "-0.5950",
        },
        {
          postalCode: "MK1 1AA",
          country: "UK" as const,
          jurisdictionIds: [ukFederalId, ukEngId],
          city: "Milton Keynes",
          stateProvince: "England",
          lat: "52.0406",
          lng: "-0.7594",
        },
        {
          postalCode: "AL1 1AA",
          country: "UK" as const,
          jurisdictionIds: [ukFederalId, ukEngId],
          city: "St Albans",
          stateProvince: "England",
          lat: "51.7527",
          lng: "-0.3394",
        },
        {
          postalCode: "CM1 1AA",
          country: "UK" as const,
          jurisdictionIds: [ukFederalId, ukEngId],
          city: "Chelmsford",
          stateProvince: "England",
          lat: "51.7356",
          lng: "0.4686",
        },
        {
          postalCode: "GU1 1AA",
          country: "UK" as const,
          jurisdictionIds: [ukFederalId, ukEngId],
          city: "Guildford",
          stateProvince: "England",
          lat: "51.2363",
          lng: "-0.5704",
        },
        {
          postalCode: "WF1 1AA",
          country: "UK" as const,
          jurisdictionIds: [ukFederalId, ukEngId],
          city: "Wakefield",
          stateProvince: "England",
          lat: "53.6833",
          lng: "-1.4977",
        },
        {
          postalCode: "OL1 1AA",
          country: "UK" as const,
          jurisdictionIds: [ukFederalId, ukEngId],
          city: "Oldham",
          stateProvince: "England",
          lat: "53.5402",
          lng: "-2.1119",
        },
        {
          postalCode: "BL1 1AA",
          country: "UK" as const,
          jurisdictionIds: [ukFederalId, ukEngId],
          city: "Bolton",
          stateProvince: "England",
          lat: "53.5769",
          lng: "-2.4282",
        },
        {
          postalCode: "WN1 1AA",
          country: "UK" as const,
          jurisdictionIds: [ukFederalId, ukEngId],
          city: "Wigan",
          stateProvince: "England",
          lat: "53.5451",
          lng: "-2.6322",
        },
        {
          postalCode: "SR1 1AA",
          country: "UK" as const,
          jurisdictionIds: [ukFederalId, ukEngId],
          city: "Sunderland",
          stateProvince: "England",
          lat: "54.9069",
          lng: "-1.3838",
        },
        {
          postalCode: "TS1 1AA",
          country: "UK" as const,
          jurisdictionIds: [ukFederalId, ukEngId],
          city: "Middlesbrough",
          stateProvince: "England",
          lat: "54.5730",
          lng: "-1.2350",
        },
        {
          postalCode: "DH1 1AA",
          country: "UK" as const,
          jurisdictionIds: [ukFederalId, ukEngId],
          city: "Durham",
          stateProvince: "England",
          lat: "54.7768",
          lng: "-1.5733",
        },
        {
          postalCode: "CA1 1AA",
          country: "UK" as const,
          jurisdictionIds: [ukFederalId, ukEngId],
          city: "Carlisle",
          stateProvince: "England",
          lat: "54.8947",
          lng: "-2.9370",
        },
        {
          postalCode: "TA1 1AA",
          country: "UK" as const,
          jurisdictionIds: [ukFederalId, ukEngId],
          city: "Taunton",
          stateProvince: "England",
          lat: "51.0190",
          lng: "-3.1010",
        },
        {
          postalCode: "GL1 1AA",
          country: "UK" as const,
          jurisdictionIds: [ukFederalId, ukEngId],
          city: "Gloucester",
          stateProvince: "England",
          lat: "51.8639",
          lng: "-2.2431",
        },
        // AU Extended (50 total)
        {
          postalCode: "3000",
          country: "AU" as const,
          jurisdictionIds: [auFederalId, auVicId],
          city: "Melbourne",
          stateProvince: "VIC",
          lat: "-37.8136",
          lng: "144.9631",
        },
        {
          postalCode: "4000",
          country: "AU" as const,
          jurisdictionIds: [auFederalId, auQldId],
          city: "Brisbane",
          stateProvince: "QLD",
          lat: "-27.4698",
          lng: "153.0251",
        },
        {
          postalCode: "6000",
          country: "AU" as const,
          jurisdictionIds: [auFederalId, auWaId],
          city: "Perth",
          stateProvince: "WA",
          lat: "-31.9505",
          lng: "115.8605",
        },
        {
          postalCode: "5000",
          country: "AU" as const,
          jurisdictionIds: [auFederalId, auSaId],
          city: "Adelaide",
          stateProvince: "SA",
          lat: "-34.9285",
          lng: "138.6007",
        },
        {
          postalCode: "7000",
          country: "AU" as const,
          jurisdictionIds: [auFederalId],
          city: "Hobart",
          stateProvince: "TAS",
          lat: "-42.8821",
          lng: "147.3272",
        },
        {
          postalCode: "0800",
          country: "AU" as const,
          jurisdictionIds: [auFederalId],
          city: "Darwin",
          stateProvince: "NT",
          lat: "-12.4634",
          lng: "130.8456",
        },
        {
          postalCode: "2300",
          country: "AU" as const,
          jurisdictionIds: [auFederalId, auNswId],
          city: "Newcastle",
          stateProvince: "NSW",
          lat: "-32.9283",
          lng: "151.7817",
        },
        {
          postalCode: "2500",
          country: "AU" as const,
          jurisdictionIds: [auFederalId, auNswId],
          city: "Wollongong",
          stateProvince: "NSW",
          lat: "-34.4278",
          lng: "150.8931",
        },
        {
          postalCode: "3128",
          country: "AU" as const,
          jurisdictionIds: [auFederalId, auVicId],
          city: "Box Hill",
          stateProvince: "VIC",
          lat: "-37.8185",
          lng: "145.1240",
        },
        {
          postalCode: "4216",
          country: "AU" as const,
          jurisdictionIds: [auFederalId, auQldId],
          city: "Gold Coast",
          stateProvince: "QLD",
          lat: "-28.0167",
          lng: "153.4000",
        },
        {
          postalCode: "4350",
          country: "AU" as const,
          jurisdictionIds: [auFederalId, auQldId],
          city: "Toowoomba",
          stateProvince: "QLD",
          lat: "-27.5598",
          lng: "151.9507",
        },
        {
          postalCode: "4700",
          country: "AU" as const,
          jurisdictionIds: [auFederalId, auQldId],
          city: "Rockhampton",
          stateProvince: "QLD",
          lat: "-23.3792",
          lng: "150.5072",
        },
        {
          postalCode: "4870",
          country: "AU" as const,
          jurisdictionIds: [auFederalId, auQldId],
          city: "Cairns",
          stateProvince: "QLD",
          lat: "-16.9186",
          lng: "145.7781",
        },
        {
          postalCode: "4800",
          country: "AU" as const,
          jurisdictionIds: [auFederalId, auQldId],
          city: "Townsville",
          stateProvince: "QLD",
          lat: "-19.2590",
          lng: "146.8169",
        },
        {
          postalCode: "3220",
          country: "AU" as const,
          jurisdictionIds: [auFederalId, auVicId],
          city: "Geelong",
          stateProvince: "VIC",
          lat: "-38.1499",
          lng: "144.3617",
        },
        {
          postalCode: "3350",
          country: "AU" as const,
          jurisdictionIds: [auFederalId, auVicId],
          city: "Ballarat",
          stateProvince: "VIC",
          lat: "-37.5622",
          lng: "143.8606",
        },
        {
          postalCode: "3550",
          country: "AU" as const,
          jurisdictionIds: [auFederalId, auVicId],
          city: "Bendigo",
          stateProvince: "VIC",
          lat: "-36.7570",
          lng: "144.2794",
        },
        {
          postalCode: "3205",
          country: "AU" as const,
          jurisdictionIds: [auFederalId, auVicId],
          city: "Melbourne",
          stateProvince: "VIC",
          lat: "-37.8409",
          lng: "144.9465",
        },
        {
          postalCode: "6008",
          country: "AU" as const,
          jurisdictionIds: [auFederalId, auWaId],
          city: "Subiaco",
          stateProvince: "WA",
          lat: "-31.9450",
          lng: "115.8250",
        },
        {
          postalCode: "6100",
          country: "AU" as const,
          jurisdictionIds: [auFederalId, auWaId],
          city: "Victoria Park",
          stateProvince: "WA",
          lat: "-31.9580",
          lng: "115.9000",
        },
        {
          postalCode: "6163",
          country: "AU" as const,
          jurisdictionIds: [auFederalId, auWaId],
          city: "Fremantle",
          stateProvince: "WA",
          lat: "-32.0569",
          lng: "115.7439",
        },
        {
          postalCode: "5031",
          country: "AU" as const,
          jurisdictionIds: [auFederalId, auSaId],
          city: "Glenelg",
          stateProvince: "SA",
          lat: "-34.9800",
          lng: "138.5210",
        },
        {
          postalCode: "5165",
          country: "AU" as const,
          jurisdictionIds: [auFederalId, auSaId],
          city: "Mount Barker",
          stateProvince: "SA",
          lat: "-35.0677",
          lng: "138.8567",
        },
        {
          postalCode: "2480",
          country: "AU" as const,
          jurisdictionIds: [auFederalId, auNswId],
          city: "Lismore",
          stateProvince: "NSW",
          lat: "-28.8113",
          lng: "153.2753",
        },
        {
          postalCode: "2444",
          country: "AU" as const,
          jurisdictionIds: [auFederalId, auNswId],
          city: "Port Macquarie",
          stateProvince: "NSW",
          lat: "-31.4308",
          lng: "152.9123",
        },
        {
          postalCode: "2485",
          country: "AU" as const,
          jurisdictionIds: [auFederalId, auNswId],
          city: "Byron Bay",
          stateProvince: "NSW",
          lat: "-28.6474",
          lng: "153.6121",
        },
        {
          postalCode: "2540",
          country: "AU" as const,
          jurisdictionIds: [auFederalId, auNswId],
          city: "Nowra",
          stateProvince: "NSW",
          lat: "-34.8806",
          lng: "150.5970",
        },
        {
          postalCode: "2795",
          country: "AU" as const,
          jurisdictionIds: [auFederalId, auNswId],
          city: "Bathurst",
          stateProvince: "NSW",
          lat: "-33.4193",
          lng: "149.5775",
        },
        {
          postalCode: "2620",
          country: "AU" as const,
          jurisdictionIds: [auFederalId],
          city: "Queanbeyan",
          stateProvince: "NSW",
          lat: "-35.3539",
          lng: "149.2318",
        },
        {
          postalCode: "7250",
          country: "AU" as const,
          jurisdictionIds: [auFederalId],
          city: "Launceston",
          stateProvince: "TAS",
          lat: "-41.4332",
          lng: "147.1441",
        },
        {
          postalCode: "7300",
          country: "AU" as const,
          jurisdictionIds: [auFederalId],
          city: "Devonport",
          stateProvince: "TAS",
          lat: "-41.1800",
          lng: "146.3500",
        },
        {
          postalCode: "0836",
          country: "AU" as const,
          jurisdictionIds: [auFederalId],
          city: "Palmerston",
          stateProvince: "NT",
          lat: "-12.4825",
          lng: "130.9850",
        },
        {
          postalCode: "0870",
          country: "AU" as const,
          jurisdictionIds: [auFederalId],
          city: "Alice Springs",
          stateProvince: "NT",
          lat: "-23.6980",
          lng: "133.8807",
        },
        {
          postalCode: "4122",
          country: "AU" as const,
          jurisdictionIds: [auFederalId, auQldId],
          city: "Brisbane",
          stateProvince: "QLD",
          lat: "-27.5670",
          lng: "153.0500",
        },
        {
          postalCode: "4123",
          country: "AU" as const,
          jurisdictionIds: [auFederalId, auQldId],
          city: "Brisbane",
          stateProvince: "QLD",
          lat: "-27.5800",
          lng: "153.0300",
        },
        {
          postalCode: "3072",
          country: "AU" as const,
          jurisdictionIds: [auFederalId, auVicId],
          city: "Preston",
          stateProvince: "VIC",
          lat: "-37.7380",
          lng: "145.0000",
        },
        {
          postalCode: "3088",
          country: "AU" as const,
          jurisdictionIds: [auFederalId, auVicId],
          city: "Greensborough",
          stateProvince: "VIC",
          lat: "-37.7080",
          lng: "145.1000",
        },
        {
          postalCode: "3109",
          country: "AU" as const,
          jurisdictionIds: [auFederalId, auVicId],
          city: "Doncaster",
          stateProvince: "VIC",
          lat: "-37.7830",
          lng: "145.1170",
        },
        {
          postalCode: "3193",
          country: "AU" as const,
          jurisdictionIds: [auFederalId, auVicId],
          city: "Brighton",
          stateProvince: "VIC",
          lat: "-37.9170",
          lng: "145.0000",
        },
        {
          postalCode: "4179",
          country: "AU" as const,
          jurisdictionIds: [auFederalId, auQldId],
          city: "Cleveland",
          stateProvince: "QLD",
          lat: "-27.5300",
          lng: "153.2700",
        },
        {
          postalCode: "4064",
          country: "AU" as const,
          jurisdictionIds: [auFederalId, auQldId],
          city: "Indooroopilly",
          stateProvince: "QLD",
          lat: "-27.5000",
          lng: "152.9700",
        },
        {
          postalCode: "6015",
          country: "AU" as const,
          jurisdictionIds: [auFederalId, auWaId],
          city: "Floreat",
          stateProvince: "WA",
          lat: "-31.9470",
          lng: "115.7980",
        },
        {
          postalCode: "6065",
          country: "AU" as const,
          jurisdictionIds: [auFederalId, auWaId],
          city: "Midland",
          stateProvince: "WA",
          lat: "-31.8900",
          lng: "116.0000",
        },
        {
          postalCode: "5045",
          country: "AU" as const,
          jurisdictionIds: [auFederalId, auSaId],
          city: " Brighton",
          stateProvince: "SA",
          lat: "-35.0300",
          lng: "138.5200",
        },
        {
          postalCode: "5061",
          country: "AU" as const,
          jurisdictionIds: [auFederalId, auSaId],
          city: "Unley",
          stateProvince: "SA",
          lat: "-34.9420",
          lng: "138.6030",
        },
        {
          postalCode: "2612",
          country: "AU" as const,
          jurisdictionIds: [auFederalId],
          city: "Belconnen",
          stateProvince: "ACT",
          lat: "-35.2380",
          lng: "149.0660",
        },
        {
          postalCode: "2903",
          country: "AU" as const,
          jurisdictionIds: [auFederalId],
          city: "Tuggeranong",
          stateProvince: "ACT",
          lat: "-35.4240",
          lng: "149.0900",
        },
        // CA Extended (50 total)
        {
          postalCode: "M5V 1A1",
          country: "CA" as const,
          jurisdictionIds: [caFederalId, caOnId],
          city: "Toronto",
          stateProvince: "ON",
          lat: "43.6532",
          lng: "-79.3832",
        },
        {
          postalCode: "H2Y 1C6",
          country: "CA" as const,
          jurisdictionIds: [caFederalId, caQcId],
          city: "Montreal",
          stateProvince: "QC",
          lat: "45.5017",
          lng: "-73.5673",
        },
        {
          postalCode: "T5J 1R8",
          country: "CA" as const,
          jurisdictionIds: [caFederalId, caAbId],
          city: "Edmonton",
          stateProvince: "AB",
          lat: "53.5461",
          lng: "-113.4938",
        },
        {
          postalCode: "T2P 1J9",
          country: "CA" as const,
          jurisdictionIds: [caFederalId, caAbId],
          city: "Calgary",
          stateProvince: "AB",
          lat: "51.0447",
          lng: "-114.0719",
        },
        {
          postalCode: "B3J 1K9",
          country: "CA" as const,
          jurisdictionIds: [caFederalId, caNsId],
          city: "Halifax",
          stateProvince: "NS",
          lat: "44.6488",
          lng: "-63.5752",
        },
        {
          postalCode: "R3C 0A8",
          country: "CA" as const,
          jurisdictionIds: [caFederalId],
          city: "Winnipeg",
          stateProvince: "MB",
          lat: "49.8951",
          lng: "-97.1384",
        },
        {
          postalCode: "S7K 1L1",
          country: "CA" as const,
          jurisdictionIds: [caFederalId],
          city: "Saskatoon",
          stateProvince: "SK",
          lat: "52.1332",
          lng: "-106.6700",
        },
        {
          postalCode: "S4P 0V7",
          country: "CA" as const,
          jurisdictionIds: [caFederalId],
          city: "Regina",
          stateProvince: "SK",
          lat: "50.4500",
          lng: "-104.6178",
        },
        {
          postalCode: "E1C 1A6",
          country: "CA" as const,
          jurisdictionIds: [caFederalId],
          city: "Moncton",
          stateProvince: "NB",
          lat: "46.0878",
          lng: "-64.7782",
        },
        {
          postalCode: "A1B 1C1",
          country: "CA" as const,
          jurisdictionIds: [caFederalId],
          city: "St. John's",
          stateProvince: "NL",
          lat: "47.5615",
          lng: "-52.7126",
        },
        {
          postalCode: "C1A 1L5",
          country: "CA" as const,
          jurisdictionIds: [caFederalId],
          city: "Charlottetown",
          stateProvince: "PE",
          lat: "46.2389",
          lng: "-63.1290",
        },
        {
          postalCode: "L2R 1E8",
          country: "CA" as const,
          jurisdictionIds: [caFederalId, caOnId],
          city: "St. Catharines",
          stateProvince: "ON",
          lat: "43.1570",
          lng: "-79.2487",
        },
        {
          postalCode: "N2H 1G6",
          country: "CA" as const,
          jurisdictionIds: [caFederalId, caOnId],
          city: "Kitchener",
          stateProvince: "ON",
          lat: "43.4516",
          lng: "-80.4925",
        },
        {
          postalCode: "N6A 1A1",
          country: "CA" as const,
          jurisdictionIds: [caFederalId, caOnId],
          city: "London",
          stateProvince: "ON",
          lat: "42.9849",
          lng: "-81.2453",
        },
        {
          postalCode: "L8N 1A1",
          country: "CA" as const,
          jurisdictionIds: [caFederalId, caOnId],
          city: "Hamilton",
          stateProvince: "ON",
          lat: "43.2557",
          lng: "-79.8711",
        },
        {
          postalCode: "P1A 1A1",
          country: "CA" as const,
          jurisdictionIds: [caFederalId, caOnId],
          city: "North Bay",
          stateProvince: "ON",
          lat: "46.3092",
          lng: "-79.4608",
        },
        {
          postalCode: "L9V 1A1",
          country: "CA" as const,
          jurisdictionIds: [caFederalId, caOnId],
          city: "Barrie",
          stateProvince: "ON",
          lat: "44.3894",
          lng: "-79.6903",
        },
        {
          postalCode: "K7L 1A1",
          country: "CA" as const,
          jurisdictionIds: [caFederalId, caOnId],
          city: "Kingston",
          stateProvince: "ON",
          lat: "44.2312",
          lng: "-76.4860",
        },
        {
          postalCode: "L4W 1A1",
          country: "CA" as const,
          jurisdictionIds: [caFederalId, caOnId],
          city: "Mississauga",
          stateProvince: "ON",
          lat: "43.5890",
          lng: "-79.6441",
        },
        {
          postalCode: "L3R 1A1",
          country: "CA" as const,
          jurisdictionIds: [caFederalId, caOnId],
          city: "Markham",
          stateProvince: "ON",
          lat: "43.8561",
          lng: "-79.3370",
        },
        {
          postalCode: "V1Y 1A1",
          country: "CA" as const,
          jurisdictionIds: [caFederalId, caBcId],
          city: "Kelowna",
          stateProvince: "BC",
          lat: "49.8880",
          lng: "-119.4960",
        },
        {
          postalCode: "V2T 1A1",
          country: "CA" as const,
          jurisdictionIds: [caFederalId, caBcId],
          city: "Abbotsford",
          stateProvince: "BC",
          lat: "49.0504",
          lng: "-122.3045",
        },
        {
          postalCode: "V8W 1A1",
          country: "CA" as const,
          jurisdictionIds: [caFederalId, caBcId],
          city: "Victoria",
          stateProvince: "BC",
          lat: "48.4284",
          lng: "-123.3656",
        },
        {
          postalCode: "V3R 1A1",
          country: "CA" as const,
          jurisdictionIds: [caFederalId, caBcId],
          city: "Surrey",
          stateProvince: "BC",
          lat: "49.1913",
          lng: "-122.8490",
        },
        {
          postalCode: "V5K 1A1",
          country: "CA" as const,
          jurisdictionIds: [caFederalId, caBcId],
          city: "Burnaby",
          stateProvince: "BC",
          lat: "49.2488",
          lng: "-122.9805",
        },
        {
          postalCode: "G1K 1A1",
          country: "CA" as const,
          jurisdictionIds: [caFederalId, caQcId],
          city: "Quebec City",
          stateProvince: "QC",
          lat: "46.8139",
          lng: "-71.2080",
        },
        {
          postalCode: "J4B 1A1",
          country: "CA" as const,
          jurisdictionIds: [caFederalId, caQcId],
          city: "Longueuil",
          stateProvince: "QC",
          lat: "45.5312",
          lng: "-73.5181",
        },
        {
          postalCode: "J7V 1A1",
          country: "CA" as const,
          jurisdictionIds: [caFederalId, caQcId],
          city: "Vaudreuil-Dorion",
          stateProvince: "QC",
          lat: "45.4000",
          lng: "-74.0333",
        },
        {
          postalCode: "J2C 1A1",
          country: "CA" as const,
          jurisdictionIds: [caFederalId, caQcId],
          city: "Saint-Jean-sur-Richelieu",
          stateProvince: "QC",
          lat: "45.3074",
          lng: "-73.2613",
        },
        {
          postalCode: "J3Y 1A1",
          country: "CA" as const,
          jurisdictionIds: [caFederalId, caQcId],
          city: "Brossard",
          stateProvince: "QC",
          lat: "45.4500",
          lng: "-73.4667",
        },
        {
          postalCode: "T1X 1A1",
          country: "CA" as const,
          jurisdictionIds: [caFederalId, caAbId],
          city: "Chestermere",
          stateProvince: "AB",
          lat: "51.0500",
          lng: "-113.8167",
        },
        {
          postalCode: "T9V 1A1",
          country: "CA" as const,
          jurisdictionIds: [caFederalId, caAbId],
          city: "Lloydminster",
          stateProvince: "AB",
          lat: "53.2833",
          lng: "-110.0000",
        },
        {
          postalCode: "T4C 1A1",
          country: "CA" as const,
          jurisdictionIds: [caFederalId, caAbId],
          city: "Airdrie",
          stateProvince: "AB",
          lat: "51.2917",
          lng: "-114.0144",
        },
        {
          postalCode: "T2N 1A1",
          country: "CA" as const,
          jurisdictionIds: [caFederalId, caAbId],
          city: "Calgary",
          stateProvince: "AB",
          lat: "51.0667",
          lng: "-114.1000",
        },
        {
          postalCode: "B2N 1A1",
          country: "CA" as const,
          jurisdictionIds: [caFederalId, caNsId],
          city: "Truro",
          stateProvince: "NS",
          lat: "45.3667",
          lng: "-63.2833",
        },
        {
          postalCode: "B4V 1A1",
          country: "CA" as const,
          jurisdictionIds: [caFederalId, caNsId],
          city: "Kentville",
          stateProvince: "NS",
          lat: "45.0778",
          lng: "-64.4958",
        },
        {
          postalCode: "B3K 1A1",
          country: "CA" as const,
          jurisdictionIds: [caFederalId, caNsId],
          city: "Halifax",
          stateProvince: "NS",
          lat: "44.6667",
          lng: "-63.5833",
        },
        {
          postalCode: "E2A 1A1",
          country: "CA" as const,
          jurisdictionIds: [caFederalId],
          city: "Bathurst",
          stateProvince: "NB",
          lat: "47.6167",
          lng: "-65.6500",
        },
        {
          postalCode: "E3B 1A1",
          country: "CA" as const,
          jurisdictionIds: [caFederalId],
          city: "Fredericton",
          stateProvince: "NB",
          lat: "45.9631",
          lng: "-66.6431",
        },
        {
          postalCode: "E1A 1A1",
          country: "CA" as const,
          jurisdictionIds: [caFederalId],
          city: "Dieppe",
          stateProvince: "NB",
          lat: "46.0781",
          lng: "-64.6883",
        },
        {
          postalCode: "R2C 1A1",
          country: "CA" as const,
          jurisdictionIds: [caFederalId],
          city: "Winnipeg",
          stateProvince: "MB",
          lat: "49.8951",
          lng: "-97.0384",
        },
        {
          postalCode: "R3L 1A1",
          country: "CA" as const,
          jurisdictionIds: [caFederalId],
          city: "Winnipeg",
          stateProvince: "MB",
          lat: "49.8667",
          lng: "-97.1167",
        },
        {
          postalCode: "S9H 1A1",
          country: "CA" as const,
          jurisdictionIds: [caFederalId],
          city: "Swift Current",
          stateProvince: "SK",
          lat: "50.2833",
          lng: "-107.8000",
        },
        {
          postalCode: "S6H 1A1",
          country: "CA" as const,
          jurisdictionIds: [caFederalId],
          city: "Moose Jaw",
          stateProvince: "SK",
          lat: "50.4000",
          lng: "-105.5333",
        },
        {
          postalCode: "V0J 1A1",
          country: "CA" as const,
          jurisdictionIds: [caFederalId, caBcId],
          city: "Prince George",
          stateProvince: "BC",
          lat: "53.9167",
          lng: "-122.7500",
        },
        {
          postalCode: "V9Z 1A1",
          country: "CA" as const,
          jurisdictionIds: [caFederalId, caBcId],
          city: "Nanaimo",
          stateProvince: "BC",
          lat: "49.1667",
          lng: "-123.9333",
        },
        {
          postalCode: "V4W 1A1",
          country: "CA" as const,
          jurisdictionIds: [caFederalId, caBcId],
          city: "Maple Ridge",
          stateProvince: "BC",
          lat: "49.2192",
          lng: "-122.5986",
        },
        {
          postalCode: "N0B 1A1",
          country: "CA" as const,
          jurisdictionIds: [caFederalId, caOnId],
          city: "Guelph",
          stateProvince: "ON",
          lat: "43.5452",
          lng: "-80.2497",
        },
        {
          postalCode: "L5A 1A1",
          country: "CA" as const,
          jurisdictionIds: [caFederalId, caOnId],
          city: "Oakville",
          stateProvince: "ON",
          lat: "43.4675",
          lng: "-79.6877",
        },
      ];

      await tx.insert(geoMappings).values(geoData);
      logInfo(`  Created ${geoData.length} geo mappings`);

      logInfo("Seed complete!");
    });
  } finally {
    await db.close();
  }
}

try {
  await seed();
} catch (err) {
  const message = err instanceof Error ? (err.stack ?? err.message) : String(err);
  logError(`Seed failed: ${message}`);
  process.exitCode = 1;
}
