import type { EligibleProgram } from "@validatehome/calculator";
import type { Country } from "@validatehome/shared";

export interface CalculatorFixture {
  name: string;
  country: Country;
  category: string;
  programs: EligibleProgram[];
  stickerPrice: number;
  householdIncome?: number;
  estimatedTaxLiability?: number;
  expectedNetCost: number;
  expectedTaxSavings: number;
  description: string;
}

export const US_HEAT_PUMP_FIXTURE: EligibleProgram[] = [
  {
    id: "us-25c-2026",
    name: "IRS 25C Heat Pump Tax Credit",
    benefitType: "tax_credit",
    maxAmount: 2000,
    percentage: null,
    perUnitAmount: null,
    incomeCap: null,
    incomePhaseoutStart: 150000,
    lifetimeLimit: null,
    annualLimit: 2000,
    currency: "USD",
    level: "federal",
    code: "25C",
    jurisdiction: "US",
    isRefundable: false,
    vatExempt: true,
  },
  {
    id: "ca-tech-2026",
    name: "California TECH Clean Energy Rebate",
    benefitType: "rebate",
    maxAmount: 7500,
    percentage: null,
    perUnitAmount: null,
    incomeCap: null,
    incomePhaseoutStart: null,
    lifetimeLimit: 7500,
    annualLimit: null,
    currency: "USD",
    level: "state",
    code: "TECH",
    jurisdiction: "US-CA",
    isRefundable: true,
    vatExempt: true,
  },
  {
    id: "pge-heat-pump",
    name: "PG&E Heat Pump Rebate",
    benefitType: "rebate",
    maxAmount: 3000,
    percentage: null,
    perUnitAmount: null,
    incomeCap: null,
    incomePhaseoutStart: null,
    lifetimeLimit: 3000,
    annualLimit: null,
    currency: "USD",
    level: "utility",
    jurisdiction: "US-CA-PGE",
    isRefundable: true,
    vatExempt: true,
  },
];

export const US_SOLAR_FIXTURE: EligibleProgram[] = [
  {
    id: "us-25d-2026",
    name: "IRS 25D Solar Tax Credit",
    benefitType: "tax_credit",
    maxAmount: null,
    percentage: 30,
    perUnitAmount: null,
    incomeCap: null,
    incomePhaseoutStart: null,
    lifetimeLimit: null,
    annualLimit: null,
    currency: "USD",
    level: "federal",
    code: "25D",
    jurisdiction: "US",
    isRefundable: false,
    vatExempt: true,
  },
];

export const UK_HEAT_PUMP_FIXTURE: EligibleProgram[] = [
  {
    id: "uk-bus-2026",
    name: "Boiler Upgrade Scheme",
    benefitType: "grant",
    maxAmount: 7500,
    percentage: null,
    perUnitAmount: null,
    incomeCap: null,
    incomePhaseoutStart: null,
    lifetimeLimit: 7500,
    annualLimit: null,
    currency: "GBP",
    level: "federal",
    code: "BUS",
    jurisdiction: "UK",
    isRefundable: true,
    vatExempt: false,
  },
  {
    id: "uk-eco4",
    name: "ECO4",
    benefitType: "grant",
    maxAmount: 16000,
    percentage: null,
    perUnitAmount: null,
    incomeCap: 31000,
    incomePhaseoutStart: null,
    lifetimeLimit: 16000,
    annualLimit: null,
    currency: "GBP",
    level: "federal",
    code: "ECO4",
    jurisdiction: "UK",
    isRefundable: true,
    vatExempt: false,
  },
];

export const UK_SOLAR_FIXTURE: EligibleProgram[] = [
  {
    id: "uk-smart-export",
    name: "Smart Export Guarantee",
    benefitType: "rebate",
    maxAmount: null,
    percentage: null,
    perUnitAmount: 0.085,
    incomeCap: null,
    incomePhaseoutStart: null,
    lifetimeLimit: null,
    annualLimit: null,
    currency: "GBP",
    level: "utility",
    code: "SEG",
    jurisdiction: "UK",
    isRefundable: true,
    vatExempt: false,
  },
];

export const AU_HEAT_PUMP_FIXTURE: EligibleProgram[] = [
  {
    id: "au-vic-heat-pump",
    name: "Victoria Heat Pump Water Heater Rebate",
    benefitType: "rebate",
    maxAmount: 1000,
    percentage: null,
    perUnitAmount: null,
    incomeCap: 180000,
    incomePhaseoutStart: null,
    lifetimeLimit: 1000,
    annualLimit: null,
    currency: "AUD",
    level: "state",
    code: "VIC-HEAT-PUMP",
    jurisdiction: "AU-VIC",
    isRefundable: true,
    vatExempt: false,
  },
];

export const AU_SOLAR_FIXTURE: EligibleProgram[] = [
  {
    id: "au-stcs-2026",
    name: "Small-scale Technology Certificates",
    benefitType: "rebate",
    maxAmount: 2500,
    percentage: null,
    perUnitAmount: null,
    incomeCap: null,
    incomePhaseoutStart: null,
    lifetimeLimit: null,
    annualLimit: null,
    currency: "AUD",
    level: "federal",
    code: "STC",
    jurisdiction: "AU",
    isRefundable: true,
    vatExempt: false,
  },
  {
    id: "au-vic-solar",
    name: "Solar Victoria Rebate",
    benefitType: "rebate",
    maxAmount: 1400,
    percentage: null,
    perUnitAmount: null,
    incomeCap: 210000,
    incomePhaseoutStart: null,
    lifetimeLimit: 1400,
    annualLimit: null,
    currency: "AUD",
    level: "state",
    code: "VIC-SOLAR",
    jurisdiction: "AU-VIC",
    isRefundable: true,
    vatExempt: false,
  },
];

export const CA_HEAT_PUMP_FIXTURE: EligibleProgram[] = [
  {
    id: "ca-greener-homes-grant",
    name: "Canada Greener Homes Grant",
    benefitType: "grant",
    maxAmount: 5000,
    percentage: null,
    perUnitAmount: null,
    incomeCap: null,
    incomePhaseoutStart: null,
    lifetimeLimit: 5000,
    annualLimit: null,
    currency: "CAD",
    level: "federal",
    code: "GREENER-HOMES-GRANT",
    jurisdiction: "CA",
    isRefundable: true,
    vatExempt: false,
  },
  {
    id: "ca-greener-homes-loan",
    name: "Canada Greener Homes Loan",
    benefitType: "loan",
    maxAmount: 40000,
    percentage: null,
    perUnitAmount: null,
    incomeCap: null,
    incomePhaseoutStart: null,
    lifetimeLimit: 40000,
    annualLimit: null,
    currency: "CAD",
    level: "federal",
    code: "GREENER-HOMES-LOAN",
    jurisdiction: "CA",
    isRefundable: true,
    vatExempt: false,
  },
  {
    id: "bc-cleanbc-heat-pump",
    name: "BC CleanBC Heat Pump Rebate",
    benefitType: "rebate",
    maxAmount: 3000,
    percentage: null,
    perUnitAmount: null,
    incomeCap: null,
    incomePhaseoutStart: null,
    lifetimeLimit: 3000,
    annualLimit: null,
    currency: "CAD",
    level: "provincial",
    code: "BC-CLEAN-BC-HP",
    jurisdiction: "CA-BC",
    isRefundable: true,
    vatExempt: false,
  },
];

export const CA_SOLAR_FIXTURE: EligibleProgram[] = [
  {
    id: "ca-greener-homes-solar",
    name: "Canada Greener Homes Grant - Solar",
    benefitType: "grant",
    maxAmount: 5000,
    percentage: null,
    perUnitAmount: null,
    incomeCap: null,
    incomePhaseoutStart: null,
    lifetimeLimit: 5000,
    annualLimit: null,
    currency: "CAD",
    level: "federal",
    code: "GREENER-HOMES-GRANT",
    jurisdiction: "CA",
    isRefundable: true,
    vatExempt: false,
  },
  {
    id: "on-saveonenergy-solar",
    name: "Ontario SaveOnEnergy Solar Rebate",
    benefitType: "rebate",
    maxAmount: 1000,
    percentage: null,
    perUnitAmount: null,
    incomeCap: null,
    incomePhaseoutStart: null,
    lifetimeLimit: 1000,
    annualLimit: null,
    currency: "CAD",
    level: "provincial",
    code: "ON-SAVEONENERGY",
    jurisdiction: "CA-ON",
    isRefundable: true,
    vatExempt: false,
  },
];

export const CALCULATOR_FIXTURES: CalculatorFixture[] = [
  {
    name: "US Heat Pump - California",
    country: "US",
    category: "heat-pump",
    programs: US_HEAT_PUMP_FIXTURE,
    stickerPrice: 15000,
    householdIncome: 120000,
    estimatedTaxLiability: 15000,
    expectedNetCost: 1500,
    expectedTaxSavings: 2000,
    description:
      "US heat pump with federal 25C credit + CA state + utility rebates. Tax credit is non-refundable, shows effective vs tax savings.",
  },
  {
    name: "US Solar - Federal Only",
    country: "US",
    category: "solar",
    programs: US_SOLAR_FIXTURE,
    stickerPrice: 25000,
    householdIncome: 100000,
    estimatedTaxLiability: 12000,
    expectedNetCost: 7500,
    expectedTaxSavings: 7500,
    description:
      "US solar with 25D tax credit (30% of system cost). Non-refundable but reduces tax liability.",
  },
  {
    name: "UK Heat Pump - BUS Only",
    country: "UK",
    category: "heat-pump",
    programs: UK_HEAT_PUMP_FIXTURE.slice(0, 1),
    stickerPrice: 12000,
    expectedNetCost: 4500,
    expectedTaxSavings: 0,
    description: "UK heat pump with BUS grant (£7,500). Not stackable with ECO4.",
  },
  {
    name: "UK Solar - SEG",
    country: "UK",
    category: "solar",
    programs: UK_SOLAR_FIXTURE,
    stickerPrice: 8000,
    expectedNetCost: 8000,
    expectedTaxSavings: 0,
    description: "UK solar with Smart Export Guarantee (per kWh export tariff, not upfront).",
  },
  {
    name: "AU Heat Pump - Victoria",
    country: "AU",
    category: "heat-pump",
    programs: AU_HEAT_PUMP_FIXTURE,
    stickerPrice: 5000,
    householdIncome: 150000,
    expectedNetCost: 4000,
    expectedTaxSavings: 0,
    description: "AU heat pump with Victorian rebate. Income cap applies above $180k.",
  },
  {
    name: "AU Solar - Victoria",
    country: "AU",
    category: "solar",
    programs: AU_SOLAR_FIXTURE,
    stickerPrice: 12000,
    householdIncome: 150000,
    expectedNetCost: 9300,
    expectedTaxSavings: 0,
    description: "AU solar with federal STCs + Victorian rebate. GST applies.",
  },
  {
    name: "CA Heat Pump - BC",
    country: "CA",
    category: "heat-pump",
    programs: CA_HEAT_PUMP_FIXTURE,
    stickerPrice: 15000,
    expectedNetCost: 7000,
    expectedTaxSavings: 0,
    description: "CA heat pump with federal grant + BC provincial. GST applies (5%+12%).",
  },
  {
    name: "CA Solar - Ontario",
    country: "CA",
    category: "solar",
    programs: CA_SOLAR_FIXTURE,
    stickerPrice: 20000,
    expectedNetCost: 18000,
    expectedTaxSavings: 0,
    description: "CA solar with federal grant + Ontario utility rebate. HST applies (13%).",
  },
];

export function getFixturesByCountry(country: Country): CalculatorFixture[] {
  return CALCULATOR_FIXTURES.filter((f) => f.country === country);
}

export function getFixturesByCategory(category: string): CalculatorFixture[] {
  return CALCULATOR_FIXTURES.filter((f) => f.category === category);
}

export function getAllFixtures(): CalculatorFixture[] {
  return CALCULATOR_FIXTURES;
}
